pipeline:
  build:
    image: frekele/ant
    secrets: [ testkey ]
    commands:
      #- ant -version
      #- java -version
      - pwd
      - echo $${TESTKEY}
      - echo ${TESTKEY}
      - wget -v
      # - ant compile jar run
