pipeline:
  restore-cache:
    image: drillster/drone-volume-cache
    restore: true
    mount:
      - ./migration_tool
    volumes:
      - /tmp/cache:/cache
    when:
      event: [ push ]

  build:
    image: frekele/ant
    secrets: [ sfusername, sfpass ]
    commands:
#      - /bin/sh get_migration_tool_file.sh
      - export SFUSR=$${SFUSERNAME}
      - export SFPSS=$${SFPASS}
#      - /bin/bash save_output_to_log.sh
    when:
      event: [ push ]

  rebuild-cache:
    image: drillster/drone-volume-cache
    rebuild: true
    mount:
      - ./migration_tool
    volumes:
      - /tmp/cache:/cache
    when:
      event: [ push ]

  e2etests:
    image: negativelypositive/nightwatch
    secrets: [ dashusername, dashpass ]
    commands:
      - export DASH_LOGIN=$${DASHUSERNAME}
      - export DASH_PASS=$${DASHPASS}
      - /bin/bash run_e2e_tests.sh
    when:
      event: [ push ] 

  notify-when-build-fails:
    image: drillster/drone-email
    host: smtp.gmail.com
    from: buildserverdroneio@example.com
    username: $EMAIL_PASSWORD
    password: $EMAIL_USERNAME
    recipients: $EMAIL_RECIPIENTS
    subject: Partner Portal build failed
    secrets: [ email_username, email_password, email_recipients ]
    body: file:///drone/src/github.com/karolkotwica/dronetest2/output.html
    when:
      status: failure 

services:
  selenium:
    image: selenium/standalone-chrome