pipeline:
  build:
    image: frekele/ant
    secrets: [ sfusername, sfpass ]
    commands:
      #- ant -version
      #- java -version
      - pwd
      - echo $${SFUSERNAME}
      - echo ${SFPASS}
      - mkdir migration_tool
      - cd migration_tool
      - wget https://gs0.salesforce.com/dwnld/SfdcAnt/salesforce_ant_41.0.zip
      - ls
      - unzip salesforce_ant_41.0.zip
      - ls
      - cd ..
      - ls
      - ant -lib migration_tool/ant-salesforce.jar -Dusername=$${SFUSERNAME} -Dpassword=$${SFPASS}
      # - ant compile jar run