pipeline:
  e2etests:
    image: negativelypositive/nightwatch
    secrets: [ dashusername, dashpass ]
    commands:
      - export DASH_LOGIN=$${DASHUSERNAME}
      - export DASH_PASS=$${DASHPASS}
      - /bin/bash run_e2e_tests.sh
    when:
      event: [ push ]

  testing-screenshots:
    commands:
      - echo 'wywolanie jak failure'
    when
      status: failure

  notify-when-build-fails:
    image: drillster/drone-email
    host: smtp.gmail.com
    from: buildserverdroneio@example.com
    username: $EMAIL_PASSWORD
    password: $EMAIL_USERNAME
    recipients: $EMAIL_RECIPIENTS
    subject: Partner Portal build failed
    secrets: [ email_username, email_password, email_recipients ]
    body: file:///drone/src/github.com/karolkotwica/dronetest2/output.html
    when:
      status: failure 

services:
  selenium:
    image: selenium/standalone-chrome