pipeline:
  restore-cache:
    image: drillster/drone-volume-cache
    restore: true
    mount:
      - ./migration_tool
    volumes:
      - /tmp/cache:/cache

  build:
    image: frekele/ant
    secrets: [ sfusername, sfpass ]
    commands:
      - /bin/sh get_migration_tool_file.sh
      # - ant -lib migration_tool/ant-salesforce.jar -Dusername=$${SFUSERNAME} -Dpassword=$${SFPASS}
      #- /bin/sh start_automated_tests.sh

  rebuild-cache:
    image: drillster/drone-volume-cache
    rebuild: true
    mount:
      - ./migration_tool
    volumes:
      - /tmp/cache:/cache

  autotest:
    image: lacucaracha/testenv:latest
    commands:
      # - docker run -i --rm --cap-add=SYS_ADMIN --name puppeteer-chrome testenv
      - node -e "cat tests.js"


#services:
#  testchrome:
#    image: lacucaracha/testenv:latest