pipeline:
  build:
    image: frekele/ant
    secrets: [ testkey ]
    commands:
      #- ant -version
      #- java -version
      - pwd
      - echo $${TESTKEY}
      - echo ${TESTKEY}
      - mkdir migration_tool
      - cd migration_tool
      # - wget https://gs0.salesforce.com/dwnld/SfdcAnt/salesforce_ant_41.0.zip
      - ls
      # - unzip salesforce_ant_41.0.zip
      - ls
      - ant -lib migration_tool/ant-salesforce.jar
      # - ant compile jar run
