pipeline:
  restore-cache:
    image: drillster/drone-volume-cache
    restore: true
    mount:
      - ./migration_tool
    volumes:
      - /tmp/cache:/cache

  build:
    image: frekele/ant
    secrets: [ sfusername, sfpass ]
    commands:
      #- /bin/sh get_migration_tool_file.sh
      #- ant -lib migration_tool/ant-salesforce.jar -Dusername=$${SFUSERNAME} -Dpassword=$${SFPASS}
      #- /bin/sh start_automated_tests.sh
      - ls

  rebuild-cache:
    image: drillster/drone-volume-cache
    rebuild: true
    mount:
      - ./migration_tool
    volumes:
      - /tmp/cache:/cache

  auto-tests:
    image: nightwatch2
    commands:
      - export SF_PASS="testlogin"
      - export SF_LOGIN="testpass"
      - export SF_TEST="testexport"
      - nightwatch tests

#  puppeteer-chrome:
    # image: puppeteer-chrome-linux
    # commands:
      # - docker run -i --rm --cap-add=SYS_ADMIN --name puppeteer-chrome testenv
      # - node -e "cat tests.js"
      # - pwd
      # - ls
      # - node -v
      # - nodejs -v
      #- ldd chrome | grep not
      #- node_modules/puppeteer/.local-chromium
      # - node tests

#services:
#  testchrome:
#    image: lacucaracha/testenv:latest

services:
  selenium:
    image: selenium/standalone-chrome