pipeline:
  restore-cache:
    image: drillster/drone-volume-cache
    restore: true
    mount:
      - ./migration_tool
    volumes:
      - /tmp/cache:/cache

  build:
    image: frekele/ant
    secrets: [ sfusername, sfpass ]
    commands:
      - "if [ -f ant-salesforce.jar ]; then
          'file exists!!!!'; 
        fi"
        
      #- /bin/sh get_migration_tool_file.sh
      #- ant -lib migration_tool/ant-salesforce.jar -Dusername=$${SFUSERNAME} -Dpassword=$${SFPASS}

  rebuild-cache:
    image: drillster/drone-volume-cache
    rebuild: true
    mount:
      - ./migration_tool
    volumes:
      - /tmp/cache:/cache      