pipeline:
  build:
    image: frekele/ant
    secrets: [ testkey ]
    commands:
      #- ant -version
      #- java -version
      - pwd
      - echo $${TESTKEY}
      - echo ${TESTKEY}
      - wget https://gs0.salesforce.com/dwnld/SfdcAnt/salesforce_ant_41.0.zip
      # - ant compile jar run
