pipeline:
  build:
    image: frekele/ant
    secrets: [ sfusername, sfpass ]
    commands:
      - /bin/bash build.sh
      - pwd
      #- mkdir migration_tool
      #- cd migration_tool
      #- wget https://gs0.salesforce.com/dwnld/SfdcAnt/salesforce_ant_41.0.zip
      #- unzip salesforce_ant_41.0.zip
      #- cd ..
      #- pwd
      - ant -lib migration_tool/ant-salesforce.jar -Dusername=$${SFUSERNAME} -Dpassword=$${SFPASS}