pipeline:
  restore-cache:
    image: drillster/drone-volume-cache
    restore: true
    mount:
      - ./migration_tool
    volumes:
      - /tmp/cache:/cache

  build:
    image: frekele/ant
    secrets: [ sfusername, sfpass ]
    commands:
      - /bin/sh get_migration_tool_file.sh
      # - ant -lib migration_tool/ant-salesforce.jar -Dusername=$${SFUSERNAME} -Dpassword=$${SFPASS}
      - ls

  notify-when-validation-error:
    image: drillster/drone-email
    host: smtp.gmail.com
    from: buildserverdroneio@example.com
    username: $EMAIL_PASSWORD
    password: $EMAIL_USERNAME
    recipients: $EMAIL_RECIPIENTS
    subject: Validation process failed
    secrets: [ email_username, email_password, email_recipients ]
    when:
      status: failure

  retrieve-profiles-from-int:
    image: frekele/ant
    secrets: [ sfusername, sfpass ]
    commands:
      - cd profiles
      - rm -f *
      - cd ../profile_migration
      - pwd
      - ant -lib ../migration_tool/ant-salesforce.jar -Dusername=$${SFUSERNAME} -Dpassword=$${SFPASS}
      - ls
      - cat package.xml      
      - cd profiles
      - ls
      - cp * ../../profiles
      - cd ../../profiles
      - pwd
      - ls

  get-and-save-profiles:
    image: docker:git
    secrets: [ gituser, gituser_name, githubtoken, githubtoken2 ]    
    commands:
      - mkdir testy
      - cd testy
      - git clone https://$${GITHUBTOKEN2}:x-oauth-basic@github.com/tenfold/salesforce-partner-portal-application.git
      - cd salesforce-partner-portal-application
      - ls
      #- git status --porcelain
      #- git config user.email "$${GITUSER}"
      #- git config user.email
      #- git config user.name "$${GITUSER_NAME}"
      #- git config user.name
      #- git config remote.origin.url https://karolkotwica:$${GITHUBTOKEN}@github.com/karolkotwica/dronetest2.git
      #- ls
      #- git remote -v
      #- git add profiles/*
      #- git status --porcelain
      #- git commit -m "test commit from drone [CI SKIP]"
      #- git log
      #- git push origin master

  rebuild-cache:
    image: drillster/drone-volume-cache
    rebuild: true
    mount:
      - ./migration_tool
    volumes:
      - /tmp/cache:/cache

  auto-tests:
    image: nightwatch2
    secrets: [ dashusername, dashpass ]
    commands:
      - export DASH_LOGIN=$${DASHUSERNAME}
      - export DASH_PASS=$${DASHPASS}
      # - nightwatch tests
      - pwd

  notify-when-e2e-tests-error:
    image: drillster/drone-email
    host: smtp.gmail.com
    from: buildserverdroneio@example.com
    username: $EMAIL_PASSWORD
    password: $EMAIL_USERNAME
    recipients: $EMAIL_RECIPIENTS
    subject: E2E testing failed
    secrets: [ email_username, email_password, email_recipients ]
    when:
      status: failure      

#services:
#  selenium:
#    image: selenium/standalone-chrome