pipeline:
  notify:
    image: drillster/drone-email
    host: smtp.gmail.com
    skip_verify: true
    username: $${MAILLOGIN}
    password: $${MAILPASS}
    from: buildserwer@droneio.com
    recipients: [ droneemailtest@gmail.com ]
    subject: drone build failed
    body: test msg
    when:
      status: [ failure ]

  restore-cache:
    image: drillster/drone-volume-cache
    restore: true
    mount:
      - ./migration_tool
    volumes:
      - /tmp/cache:/cache

  build:
    image: frekele/ant
    secrets: [ sfusername, sfpass ]
    commands:
      - /bin/sh get_migration_tool_file.sh
      - ant -lib migration_tool/ant-salesforce.jar -Dusername=$${SFUSERNAME} -Dpassword=$${SFPASS}

  rebuild-cache:
    image: drillster/drone-volume-cache
    rebuild: true
    mount:
      - ./migration_tool
    volumes:
      - /tmp/cache:/cache

  auto-tests:
    image: nightwatch2
    secrets: [ dashusername, dashpass ]
    commands:      
      - export DASH_LOGIN=$${DASHUSERNAME}
      - export DASH_PASS=$${DASHPASS}
      - nightwatch tests

services:
  selenium:
    image: selenium/standalone-chrome